/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TrackRouteImport } from "./routes/track";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AdminRouteRouteImport } from "./routes/_admin/route";
import { Route as AdminIndexRouteImport } from "./routes/_admin/index";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AdminUsersRouteImport } from "./routes/_admin/users";
import { Route as AdminTransactionsRouteImport } from "./routes/_admin/transactions";
import { Route as AdminStoresRouteImport } from "./routes/_admin/stores";
import { Route as AdminServicesRouteImport } from "./routes/_admin/services";
import { Route as AdminProductsRouteImport } from "./routes/_admin/products";
import { Route as AdminPaymentMethodsRouteImport } from "./routes/_admin/payment-methods";
import { Route as AdminCustomersRouteImport } from "./routes/_admin/customers";
import { Route as AdminCategoriesRouteImport } from "./routes/_admin/categories";
import { Route as AdminCampaignsRouteImport } from "./routes/_admin/campaigns";
import { Route as AdminWorkerIndexRouteImport } from "./routes/_admin/worker.index";
import { Route as AdminOrdersIndexRouteImport } from "./routes/_admin/orders.index";
import { Route as AdminOrdersNewRouteImport } from "./routes/_admin/orders.new";
import { Route as AdminOrdersOrderIdRouteImport } from "./routes/_admin/orders.$orderId";

const TrackRoute = TrackRouteImport.update({
  id: "/track",
  path: "/track",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/_admin",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: "/stores",
  path: "/stores",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: "/payment-methods",
  path: "/payment-methods",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: "/campaigns",
  path: "/campaigns",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminWorkerIndexRoute = AdminWorkerIndexRouteImport.update({
  id: "/worker/",
  path: "/worker/",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: "/orders/new",
  path: "/orders/new",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => AdminRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AdminIndexRoute;
  "/login": typeof LoginRoute;
  "/track": typeof TrackRoute;
  "/campaigns": typeof AdminCampaignsRoute;
  "/categories": typeof AdminCategoriesRoute;
  "/customers": typeof AdminCustomersRoute;
  "/payment-methods": typeof AdminPaymentMethodsRoute;
  "/products": typeof AdminProductsRoute;
  "/services": typeof AdminServicesRoute;
  "/stores": typeof AdminStoresRoute;
  "/transactions": typeof AdminTransactionsRoute;
  "/users": typeof AdminUsersRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/orders/$orderId": typeof AdminOrdersOrderIdRoute;
  "/orders/new": typeof AdminOrdersNewRoute;
  "/orders/": typeof AdminOrdersIndexRoute;
  "/worker/": typeof AdminWorkerIndexRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/track": typeof TrackRoute;
  "/campaigns": typeof AdminCampaignsRoute;
  "/categories": typeof AdminCategoriesRoute;
  "/customers": typeof AdminCustomersRoute;
  "/payment-methods": typeof AdminPaymentMethodsRoute;
  "/products": typeof AdminProductsRoute;
  "/services": typeof AdminServicesRoute;
  "/stores": typeof AdminStoresRoute;
  "/transactions": typeof AdminTransactionsRoute;
  "/users": typeof AdminUsersRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/": typeof AdminIndexRoute;
  "/orders/$orderId": typeof AdminOrdersOrderIdRoute;
  "/orders/new": typeof AdminOrdersNewRoute;
  "/orders": typeof AdminOrdersIndexRoute;
  "/worker": typeof AdminWorkerIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_admin": typeof AdminRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/track": typeof TrackRoute;
  "/_admin/campaigns": typeof AdminCampaignsRoute;
  "/_admin/categories": typeof AdminCategoriesRoute;
  "/_admin/customers": typeof AdminCustomersRoute;
  "/_admin/payment-methods": typeof AdminPaymentMethodsRoute;
  "/_admin/products": typeof AdminProductsRoute;
  "/_admin/services": typeof AdminServicesRoute;
  "/_admin/stores": typeof AdminStoresRoute;
  "/_admin/transactions": typeof AdminTransactionsRoute;
  "/_admin/users": typeof AdminUsersRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/_admin/": typeof AdminIndexRoute;
  "/_admin/orders/$orderId": typeof AdminOrdersOrderIdRoute;
  "/_admin/orders/new": typeof AdminOrdersNewRoute;
  "/_admin/orders/": typeof AdminOrdersIndexRoute;
  "/_admin/worker/": typeof AdminWorkerIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/track"
    | "/campaigns"
    | "/categories"
    | "/customers"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/transactions"
    | "/users"
    | "/auth/login"
    | "/orders/$orderId"
    | "/orders/new"
    | "/orders/"
    | "/worker/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/track"
    | "/campaigns"
    | "/categories"
    | "/customers"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/transactions"
    | "/users"
    | "/auth/login"
    | "/"
    | "/orders/$orderId"
    | "/orders/new"
    | "/orders"
    | "/worker";
  id:
    | "__root__"
    | "/_admin"
    | "/login"
    | "/track"
    | "/_admin/campaigns"
    | "/_admin/categories"
    | "/_admin/customers"
    | "/_admin/payment-methods"
    | "/_admin/products"
    | "/_admin/services"
    | "/_admin/stores"
    | "/_admin/transactions"
    | "/_admin/users"
    | "/auth/login"
    | "/_admin/"
    | "/_admin/orders/$orderId"
    | "/_admin/orders/new"
    | "/_admin/orders/"
    | "/_admin/worker/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  TrackRoute: typeof TrackRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/track": {
      id: "/track";
      path: "/track";
      fullPath: "/track";
      preLoaderRoute: typeof TrackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin": {
      id: "/_admin";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AdminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin/": {
      id: "/_admin/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin/users": {
      id: "/_admin/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/transactions": {
      id: "/_admin/transactions";
      path: "/transactions";
      fullPath: "/transactions";
      preLoaderRoute: typeof AdminTransactionsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/stores": {
      id: "/_admin/stores";
      path: "/stores";
      fullPath: "/stores";
      preLoaderRoute: typeof AdminStoresRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/services": {
      id: "/_admin/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof AdminServicesRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/products": {
      id: "/_admin/products";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof AdminProductsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/payment-methods": {
      id: "/_admin/payment-methods";
      path: "/payment-methods";
      fullPath: "/payment-methods";
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/customers": {
      id: "/_admin/customers";
      path: "/customers";
      fullPath: "/customers";
      preLoaderRoute: typeof AdminCustomersRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/categories": {
      id: "/_admin/categories";
      path: "/categories";
      fullPath: "/categories";
      preLoaderRoute: typeof AdminCategoriesRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/campaigns": {
      id: "/_admin/campaigns";
      path: "/campaigns";
      fullPath: "/campaigns";
      preLoaderRoute: typeof AdminCampaignsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/worker/": {
      id: "/_admin/worker/";
      path: "/worker";
      fullPath: "/worker/";
      preLoaderRoute: typeof AdminWorkerIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/orders/": {
      id: "/_admin/orders/";
      path: "/orders";
      fullPath: "/orders/";
      preLoaderRoute: typeof AdminOrdersIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/orders/new": {
      id: "/_admin/orders/new";
      path: "/orders/new";
      fullPath: "/orders/new";
      preLoaderRoute: typeof AdminOrdersNewRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/orders/$orderId": {
      id: "/_admin/orders/$orderId";
      path: "/orders/$orderId";
      fullPath: "/orders/$orderId";
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
  }
}

interface AdminRouteRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute;
  AdminCategoriesRoute: typeof AdminCategoriesRoute;
  AdminCustomersRoute: typeof AdminCustomersRoute;
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute;
  AdminProductsRoute: typeof AdminProductsRoute;
  AdminServicesRoute: typeof AdminServicesRoute;
  AdminStoresRoute: typeof AdminStoresRoute;
  AdminTransactionsRoute: typeof AdminTransactionsRoute;
  AdminUsersRoute: typeof AdminUsersRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute;
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute;
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute;
  AdminWorkerIndexRoute: typeof AdminWorkerIndexRoute;
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminWorkerIndexRoute: AdminWorkerIndexRoute,
};

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  AuthLoginRoute: AuthLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
